### ISSUE TITLE
Q: how can another language (e.g. Python) talk to this json-rpc server?

### ISSUE THREAD

**Issue by mw66** [rjframe/json-rpc#13]
Q: how can another language (e.g. Python) talk to this json-rpc server?

Any code examples?

Thanks.

**Comment by mw66** [comment]
Tried this:

```
$ pip install jsonrpctcp

$ python3
>>> from jsonrpctcp import connect                                                     
>>> conn = connect('localhost', 54321)                                                 
>>> result = conn.printGreeting("Some Person!");                       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>                          
...
File "/lib/python3.9/site-packages/jsonrpctcp/client.py", line 173, in _send_and_receive
    response = b''.join(responselist)                                                                                                                                         
TypeError: sequence item 0: expected a bytes-like object, str found

```
